# Form implementation generated from reading ui file 'design/ui_files/article_creation.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ArticleCreationWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 301)
        MainWindow.setStyleSheet('color: black;')
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 911, 571))
        self.frame.setStyleSheet("background: rgb(141, 141, 141);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(200, 0, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.create_article = QtWidgets.QPushButton(parent=self.frame)
        self.create_article.setGeometry(QtCore.QRect(140, 150, 541, 61))
        self.create_article.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_article.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.create_article.setObjectName("create_article")
        self.article_title = QtWidgets.QLineEdit(parent=self.frame)
        self.article_title.setGeometry(QtCore.QRect(190, 70, 441, 61))
        self.article_title.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"color: black;\n"
"padding-left: 5px;")
        self.article_title.setObjectName("article_title")
        self.back = QtWidgets.QPushButton(parent=self.frame)
        self.back.setGeometry(QtCore.QRect(140, 220, 541, 61))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NotePedia"))
        self.label.setText(_translate("MainWindow", "Створити статью"))
        self.create_article.setText(_translate("MainWindow", "Створити статью"))
        self.article_title.setPlaceholderText(_translate("MainWindow", "Заголовок"))
        self.back.setText(_translate("MainWindow", "Назад"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
