# Form implementation generated from reading ui file 'design/ui_files/articles_view.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ArticlesViewWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 506)
        MainWindow.setStyleSheet('color: black;')
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 951, 591))
        self.frame.setStyleSheet("background: rgb(141, 141, 141);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(250, 10, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.main_menu = QtWidgets.QPushButton(parent=self.frame)
        self.main_menu.setGeometry(QtCore.QRect(30, 440, 471, 61))
        self.main_menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.main_menu.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.main_menu.setObjectName("main_menu")
        self.search_request = QtWidgets.QLineEdit(parent=self.frame)
        self.search_request.setGeometry(QtCore.QRect(530, 120, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        self.search_request.setFont(font)
        self.search_request.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"color: black;\n"
"padding-left: 5px;")
        self.search_request.setObjectName("search_request")
        self.search = QtWidgets.QPushButton(parent=self.frame)
        self.search.setGeometry(QtCore.QRect(530, 180, 251, 51))
        self.search.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.search.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.search.setObjectName("search")
        self.open_article = QtWidgets.QPushButton(parent=self.frame)
        self.open_article.setGeometry(QtCore.QRect(30, 370, 471, 61))
        self.open_article.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.open_article.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.open_article.setObjectName("open_article")
        self.show_all_articles = QtWidgets.QPushButton(parent=self.frame)
        self.show_all_articles.setGeometry(QtCore.QRect(530, 240, 251, 51))
        self.show_all_articles.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.show_all_articles.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.show_all_articles.setObjectName("show_all_articles")
        self.articles = QtWidgets.QListWidget(parent=self.frame)
        self.articles.setGeometry(QtCore.QRect(20, 70, 491, 281))
        self.articles.setStyleSheet("background: white;\n"
"border-radius: 20px;")
        self.articles.setObjectName("articles")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NotePedia"))
        self.label.setText(_translate("MainWindow", "Перегляд статей"))
        self.main_menu.setText(_translate("MainWindow", "Головне меню"))
        self.search_request.setPlaceholderText(_translate("MainWindow", "Пошук"))
        self.search.setText(_translate("MainWindow", "Пошук"))
        self.open_article.setText(_translate("MainWindow", "Відкрити"))
        self.show_all_articles.setText(_translate("MainWindow", "Показати всі статьї"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
