# Form implementation generated from reading ui file 'design/ui_files/edit_article.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class EditArticleWindowDesign(object):
    def setupUi(self, Wikipedia):
        Wikipedia.setObjectName("Wikipedia")
        Wikipedia.resize(919, 536)
        Wikipedia.setStyleSheet("color: black;")
        self.centralwidget = QtWidgets.QWidget(parent=Wikipedia)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 931, 551))
        self.frame.setStyleSheet("background: rgb(141, 141, 141);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(230, 0, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.create_new_article = QtWidgets.QPushButton(parent=self.frame)
        self.create_new_article.setGeometry(QtCore.QRect(210, 450, 171, 61))
        self.create_new_article.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_new_article.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.create_new_article.setObjectName("create_new_article")
        self.article_title = QtWidgets.QLineEdit(parent=self.frame)
        self.article_title.setGeometry(QtCore.QRect(20, 70, 901, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.article_title.setFont(font)
        self.article_title.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"color: black;\n"
"padding-left: 5px;")
        self.article_title.setObjectName("article_title")
        self.view_other_articles = QtWidgets.QPushButton(parent=self.frame)
        self.view_other_articles.setGeometry(QtCore.QRect(20, 450, 181, 61))
        self.view_other_articles.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.view_other_articles.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.view_other_articles.setObjectName("view_other_articles")
        self.save_article = QtWidgets.QPushButton(parent=self.frame)
        self.save_article.setGeometry(QtCore.QRect(740, 450, 171, 61))
        self.save_article.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_article.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.save_article.setObjectName("save_article")
        self.content = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.content.setGeometry(QtCore.QRect(23, 158, 891, 271))
        self.content.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"color: black;\n"
"padding-left: 5px;\n"
"padding-top: 5px;")
        self.content.setObjectName("content")
        self.delete_article = QtWidgets.QPushButton(parent=self.frame)
        self.delete_article.setGeometry(QtCore.QRect(550, 450, 171, 61))
        self.delete_article.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_article.setStyleSheet("QPushButton {\n"
"    background: rgb(108, 108, 108);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(124, 124, 124);\n"
"}")
        self.delete_article.setObjectName("delete_article")
        Wikipedia.setCentralWidget(self.centralwidget)

        self.retranslateUi(Wikipedia)
        QtCore.QMetaObject.connectSlotsByName(Wikipedia)

    def retranslateUi(self, Wikipedia):
        _translate = QtCore.QCoreApplication.translate
        Wikipedia.setWindowTitle(_translate("Wikipedia", "NotePedia"))
        self.label.setText(_translate("Wikipedia", "Редагування статьї"))
        self.create_new_article.setText(_translate("Wikipedia", "Створити нову статью"))
        self.article_title.setPlaceholderText(_translate("Wikipedia", "Заголовок"))
        self.view_other_articles.setText(_translate("Wikipedia", "Переглянути інші статьї"))
        self.save_article.setText(_translate("Wikipedia", "Зберегти"))
        self.content.setPlaceholderText(_translate("Wikipedia", "Введіть сюди текст статьї"))
        self.delete_article.setText(_translate("Wikipedia", "Видалити статью"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Wikipedia = QtWidgets.QMainWindow()
#     ui = Ui_Wikipedia()
#     ui.setupUi(Wikipedia)
#     Wikipedia.show()
#     sys.exit(app.exec())
